services:
  sveltefrontend-dev:
    container_name: sveltefrontendcontainer-dev
    build:
      context: ./sveltefrontend
      dockerfile: Dockerfile_dev
    expose:
      - "5173"
    volumes:
      - ./sveltefrontend:/app
    networks:
      - app-network
  
  sveltefrontend:
    container_name: sveltefrontendcontainer
    build:
      context: ./sveltefrontend
    expose:
      - "3000"
    networks:
      - app-network
  
  nginx-dev:
    image: nginx:alpine
    container_name: nginxcontainer-dev
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginxcontainer
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
