services:
  svelte-app:
    build: 
      context: ./Svelte-files
      target: ${SERVER_ENV:-development}  # Use SERVER_ENV from .env or default to development
    container_name: svelte
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./Svelte-files:/app
      - /app/node_modules
      - /app/.vite
      - /app/.svelte-kit 
    depends_on:
      - redis
      - websocket-server
    environment:
      - VITE_WEBSOCKET_URL=${WEBSOCKET_URL}
    restart: unless-stopped
  
  redis:
    build: ./Redis-files
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./Redis-files/data:/data
    restart: unless-stopped

  websocket-server:
    build: ./redis-websocket-server
    container_name: node-websocket
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "try{require('http').get('http://localhost:8080/health',r=>r.statusCode==200?process.exit(0):process.exit(1))}catch(e){process.exit(1)}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s