version: '3.8'

services:
  svelte-app:
    build: ./Svelte-files
    container_name: svelte
    ports:
      - "5173:5173"  # Expose the dev server
    volumes:
      - ./Svelte-files:/app  # Sync local changes
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      - redis
  
  redis:
    build: ./Redis-files
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  websocket-server:
    build: ./redis-websocket-server
    container_name: node-websocket
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
    restart: unless-stopped

volumes:
  redis-data: