services:
  svelte-app-prod:
    build: 
      context: ./Svelte-files
      target: production
      args: 
        - VITE_APP_WEBSOCKET_URL=${APP_WEBSOCKET_URL}
    container_name: svelte
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - websocket-server
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - prod
  
  svelte-app-dev:
    build: 
      context: ./Svelte-files
      target: development
    environment:
      - VITE_APP_WEBSOCKET_URL=${APP_WEBSOCKET_URL}
      - HOST=0.0.0.0
    volumes:
      - ./Svelte-files:/app
    container_name: svelte
    ports:
      - "5173:5173"
    depends_on:
      - redis
      - websocket-server
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev
  
  redis:
    build: ./Redis-files
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./Redis-files/data:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  websocket-server:
    build: ./redis-websocket-server
    container_name: node-websocket
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "try{require('http').get('http://localhost:8080/health',r=>r.statusCode==200?process.exit(0):process.exit(1))}catch(e){process.exit(1)}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    volumes:
      - ./redis-websocket-server:/app
      - /app/node_modules
networks:
  app-network: