version: '3.8'

services:
  svelte-app:
    build: ./Svelte-files
    container_name: svelte
    ports:
      - "5173:5173"
    volumes:
      - ./Svelte-files:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - VITE_WEBSOCKET_URL=${WEBSOCKET_URL}

    restart: unless-stopped
  
  redis:
    build: ./Redis-files
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  websocket-server:
    build: ./redis-websocket-server
    container_name: node-websocket
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

volumes:
  redis-data: