export const itemList = [
    'Elli Dunbar', 
    'Happy Together', 
    'Harvoin mä ryypyn saan',
    'Hauen laulu',
    'Hiiden orjien laulu',
    'Hiprakassa',
    'Hämärän ääniä',
    'In these Delightful Pleasant Groves',
    'Isänmaalle',
    'Jesu Dulcis',
    'Joulun virsi, elämän virsi',
    'Juhannus',
    'Kaksi laulua kuolemasta',
    'Keinu',
    'Kuu',
    'Kuutamolla',
    'Käy isänmaataan kohti \'ain',
    'Gut Singer und ein Organist',
    'Ljuva flicka',
    'Madrigaali',
    'Sjöfararen vid milan',
    'Metsämiehen laulu',
    'Nattlig madonna',
    'Now is the Month of Maying',
    'Nuijamiesten marssi',
    'Onnelliset',
    'Hiien hiilien sekahan',
    'Santa Maria',
    'Se nukku',
    'Soita somer, helkä hiekka',
    'Sortunut ääni',
    'Suvi-llan vieno tuuli',
    'Tanssista palataan',
    'Tanssit',
    'Tre sånger om kärleken',
    'Trinklied aus dem 16. Jahrhundert',
    'Tuutulaulu',
    'Uti vår hage',
    'Veljesten paluu Jukolaan',
    'Virta venhettä vie'
];

export const userList = [
    'Martti',
    'Eelis',
    'Keinis',
    'Jan'
]