name: cd

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: 
          docker compose build sveltefrontend nginx
        working-directory: ./
      
      - name: Tag and push to Docker Hub
        run: |
          docker tag sdcprogresstracker-sveltefrontend:latest ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-sveltefrontend:latest
          docker tag sdcprogresstracker-nginx:latest ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-nginx:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-sveltefrontend:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-nginx:latest