name: cd

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: 
          docker compose build sveltefrontend nginx
        working-directory: ./ 